import { AuthButton } from "@/components/custom/auth/auth-button";
import { AuthUserNavButton } from "@/components/custom/auth/auth-user-button";
import { Button } from "@/components/ui/button";
import { getUserMeLoader } from "@/lib/hooks/services/get-user-me-loader";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserMeLoader();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex items-center justify-between p-4">
          <h1>At Store</h1>
          {user?.data ? (
            <AuthUserNavButton user={user.data} />
          ) : (
            <Button asChild>
              <AuthButton />
            </Button>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
